# Generated by Django 5.1.7 on 2025-03-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0002_populate_initial_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="logo_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
