# Generated by Django 5.1.7 on 2025-03-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0003_tool_logo_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tool",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="tool",
            name="tools_tool_name_3f7e14_idx",
        ),
        migrations.RemoveIndex(
            model_name="tool",
            name="tools_tool_descrip_b596cf_idx",
        ),
        migrations.RemoveField(
            model_name="tool",
            name="logo_url",
        ),
        migrations.AddField(
            model_name="tool",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="tool_logos/"),
        ),
        migrations.AlterField(
            model_name="tool",
            name="tags",
            field=models.ManyToManyField(related_name="tools", to="tools.tag"),
        ),
    ]
